// Code generated by encore. DO NOT EDIT.

package site

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Add adds a new site to the list of monitored websites.
func Add(ctx context.Context, p *AddParams) (*Site, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Site)(nil), nil
}

// Delete deletes a site by id.
func Delete(ctx context.Context, siteID int) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// Get gets a site by id.
func Get(ctx context.Context, siteID int) (*Site, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Site)(nil), nil
}

// List lists the monitored websites.
func List(ctx context.Context) (*ListResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ListResponse)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// Add adds a new site to the list of monitored websites.
	Add(ctx context.Context, p *AddParams) (*Site, error)

	// Delete deletes a site by id.
	Delete(ctx context.Context, siteID int) error

	// Get gets a site by id.
	Get(ctx context.Context, siteID int) (*Site, error)

	// List lists the monitored websites.
	List(ctx context.Context) (*ListResponse, error)
}
