// Code generated by encore. DO NOT EDIT.

package monitor

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// Check checks a single site.
	Check(ctx context.Context, siteID int) error

	// CheckAll checks all sites.
	CheckAll(ctx context.Context) error

	// Ping pings a specific site and determines whether it's up or down right now.
	Ping(ctx context.Context, url string) (*PingResponse, error)

	// Status checks the current up/down status of all monitored sites.
	Status(ctx context.Context) (*StatusResponse, error)
}
